name: Run Reddit → Discord Bot Daily

on:
  schedule:
    - cron: '35 14 * * *'  # Runs every day at 14:35 UTC (adjust to your local time)
on:
  workflow_dispatch:  # This allows manual runs

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install praw requests

      - name: Run bot script
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python your_bot_file.py
